# Generated by Django 6.0 on 2025-12-16 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('imdb_id', models.CharField(help_text='e.g., tt0468569', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('synopsis', models.TextField(blank=True)),
                ('poster_url', models.URLField(blank=True, max_length=1000)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('source_site', models.CharField(blank=True, help_text='e.g., makemoviestreaming.com', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StreamingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_url', models.URLField(max_length=1000)),
                ('quality', models.CharField(default='Unknown', max_length=50)),
                ('language', models.CharField(default='EN', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='streaming.movie')),
            ],
            options={
                'unique_together': {('movie', 'stream_url')},
            },
        ),
    ]
