# Generated by Django 4.2.27 on 2025-12-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_alter_streaminglink_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaminglink',
            name='check_count',
            field=models.IntegerField(default=0, help_text='Number of times this link has been checked'),
        ),
        migrations.AddField(
            model_name='streaminglink',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if link is broken'),
        ),
        migrations.AddField(
            model_name='streaminglink',
            name='server_name',
            field=models.CharField(default='Unknown', help_text='e.g., Dood, Luluvdo, Vidsrc', max_length=50),
        ),
    ]
