# Generated by Django 4.2.27 on 2025-12-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_streaminglink_check_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='episode_number',
            field=models.IntegerField(blank=True, help_text='Episode number', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='episode_title',
            field=models.CharField(blank=True, help_text='Episode title', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_series',
            field=models.BooleanField(default=False, help_text='True if this is a series'),
        ),
        migrations.AddField(
            model_name='movie',
            name='season_number',
            field=models.IntegerField(blank=True, help_text='Season number for episodes', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='series_imdb_id',
            field=models.CharField(blank=True, help_text='IMDb ID of the main series', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='series_name',
            field=models.CharField(blank=True, help_text='Series name for episodes', max_length=255),
        ),
    ]
