# Generated by Django 4.2.27 on 2025-12-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_movie_episode_number_movie_episode_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='episodes_data',
            field=models.TextField(blank=True, help_text='JSON data containing all episodes information'),
        ),
    ]
