# Generated by Django 4.2.27 on 2025-12-20 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_movie_episodes_data'),
    ]

    operations = [
    ]
