# Generated by Django 4.2.27 on 2025-12-20 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0006_auto_20251220_1019'),
        ('streaming', '0006_remove_series_fields'),
    ]

    operations = [
    ]
