# Generated by Django 4.2.27 on 2025-12-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0007_merge_20251220_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='episode_number',
            field=models.IntegerField(blank=True, help_text='Episode number (for episodes)', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='episode_title',
            field=models.CharField(blank=True, help_text='Title of the episode (for episodes)', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='episodes_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON data storing all seasons and episodes for series'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_series',
            field=models.BooleanField(default=False, help_text='True if this is a series with multiple episodes'),
        ),
        migrations.AddField(
            model_name='movie',
            name='season_number',
            field=models.IntegerField(blank=True, help_text='Season number (for episodes)', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='series_imdb_id',
            field=models.CharField(blank=True, help_text='IMDb ID of the main series (for episodes)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='series_name',
            field=models.CharField(blank=True, help_text='Name of the series (for episodes)', max_length=255),
        ),
    ]
