# Generated by Django 4.2.27 on 2025-12-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0008_add_series_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='episodes_data',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='episode_number',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='episode_title',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='is_series',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='season_number',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='series_imdb_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='series_name',
        ),
    ]
