# Generated by Django 6.0 on 2025-12-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0009_remove_series_fields_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('series', 'Series')], default='movie', help_text='Movie or Series', max_length=10),
        ),
        migrations.AlterField(
            model_name='streaminglink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
