# Generated by Django 4.2.27 on 2025-12-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0010_movie_content_type_alter_streaminglink_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.CharField(blank=True, help_text='Comma-separated genres', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_average',
            field=models.FloatField(default=0.0, help_text='TMDB rating'),
        ),
        migrations.AlterField(
            model_name='streaminglink',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
