# Generated by Django 6.0 on 2025-12-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0011_movie_genres_movie_release_date_movie_vote_average_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streaminglink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
