# Generated by Django 6.0 on 2025-12-29 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0012_alter_streaminglink_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='vote_average',
        ),
    ]
