# Generated by Django 4.2.27 on 2025-12-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0013_remove_movie_genres_remove_movie_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text="Extra data like season counts e.g. {'seasons': [{'season_number': 1, 'episode_count': 10}]}"),
        ),
        migrations.AlterField(
            model_name='streaminglink',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
