# Generated by Django 4.2.27 on 2025-12-30 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0016_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
