# Generated by Django 4.2.27 on 2025-12-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0017_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('series', 'Series')], db_index=True, default='movie', help_text='Movie or Series', max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='streaminglink',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
