# Generated by Django 4.2.27 on 2025-12-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0018_alter_movie_content_type_alter_movie_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre_list',
            field=models.CharField(blank=True, db_index=True, help_text='Comma-separated genres for fast filtering', max_length=500),
        ),
    ]
