# Generated by Django 4.2.27 on 2025-12-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0020_alter_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(db_index=True, default='Released', help_text='e.g., Released, Upcoming, Post Production', max_length=50),
        ),
    ]
